# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'recWAV' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'DGElasticPullToRefresh'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'Luminous'
  pod 'ShortCode'
  pod 'VersionsTracker'
  pod 'SideMenu'

# Pods for recWAV

  target 'recWAVTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'recWAVUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
